before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - '386'
      - amd64
      - arm64
    goarm:
      - '6'
    binary: wylogger

archives:
  - format: zip
    format_overrides:
      - goos: darwin
        format: tar.gz
      - goos: linux
        format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - README.zh-CN.md
      - config.example.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
  
changelog:
  skip: false

brews:
  - 
    tap:
      owner: mafuka
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/mafuka/wylogger"
    description: "A tool for automatically authenticate the network of Wen Yuan Talent Apartment."
    install: |
      bin.install "wylogger"
      libexec.install "config.example.yml"
    post_install: |
      unless (etc/"wylogger/config.yml").exist?
        (etc/"wylogger").mkpath
        etc.install_symlink libexec/"config.example.yml" => "wylogger/config.yml"
      end
      puts "Please customize your configuration file at #{etc/"wylogger/config.yml"}"
