# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wylogger < Formula
  desc "A tool for automatically authenticate the network of Wen Yuan Talent Apartment."
  homepage "https://github.com/mafuka/wylogger"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.2/wylogger_darwin_arm64.tar.gz"
      sha256 "815937abe42d7ee7b33f8e4d55daa182a97c67978d38cf7cec14472ca9bda651"

      def install
        bin.install "wylogger"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.2/wylogger_darwin_amd64.tar.gz"
      sha256 "43c32215beea210200e7a52780e3a2e7cb95704ff4c5b8c6792b38682ccf8442"

      def install
        bin.install "wylogger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.2/wylogger_linux_amd64.tar.gz"
      sha256 "70c2281299e860e53f7fe6d23e6eb23305fd6a49c6f51e10ae271adb0a417523"

      def install
        bin.install "wylogger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.2/wylogger_linux_arm64.tar.gz"
      sha256 "8d7988c4106d71232512907e0097304bef86d5fc04cde5803361de953255215d"

      def install
        bin.install "wylogger"
      end
    end
  end

  def post_install
    (etc/"wylogger").mkpath
    unless (etc/"wylogger/config.yml").exist?
      cp "pkgshare/config.example.yml", etc/"wylogger/config.yml"
    end
    puts "Please customize your configuration file at #{etc/"wylogger/config.yml"}"
  end
end
